### ISSUE TITLE
The get_config() function fails when branching plugin is installed

### ISSUE THREAD

**Issue by rcrawf** [netboxlabs/netbox-branching#101]
### Plugin Version

0.4.0

### NetBox Version

4.1.0

### Python Version

3.12

### Steps to Reproduce

- Install branching plugin as per the docs
- In any NetBox plugin, try use the `get_config()` function during the `__init__` process.

For example, in a plugin's `__init__.py` file (I used the one in the branching plugin, but I observed the same result in different plugins too):

```
    def ready(self):
        from netbox.config import get_config
        config = get_config()
        super().ready()
```

Then run `manage.py` without any args and it throws an exception.

Note: If the branching plugin is not installed, running `get_config()` in the `__init__` works of a plugin as expected. 

### Expected Behavior

I should see no errors and a 0 exit code.

### Observed Behavior

I see the following exception:

```
# ./manage.py 
Traceback (most recent call last):
  File "/opt/netbox/netbox/./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/opt/netbox/venv/lib/python3.11/site-packages/netbox_branching/__init__.py", line 28, in ready
    get_config()
  File "/opt/netbox/netbox/netbox/config/__init__.py", line 28, in get_config
    _thread_locals.config = Config()
                            ^^^^^^^^
  File "/opt/netbox/netbox/netbox/config/__init__.py", line 50, in __init__
    self._populate_from_db()
  File "/opt/netbox/netbox/netbox/config/__init__.py", line 81, in _populate_from_db
    revision = ConfigRevision.objects.last()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1110, in last
    for obj in queryset[:1]:
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/models/query.py", line 400, in __iter__
    self._fetch_all()
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/models/query.py", line 87, in __iter__
    db = queryset.db
         ^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1816, in db
    return self._db or router.db_for_read(self.model, **self._hints)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/utils.py", line 227, in _route_db
    chosen_db = method(model, **hints)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/netbox_branching/database.py", line 27, in db_for_read
    return self._get_db(model, **hints)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/netbox_branching/database.py", line 19, in _get_db
    if model_name not in registry['model_features']['branching'].get(app_label, []):
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'branching'
```

**Comment by jeremystretch** [comment]
The error is raised because NetBox is attempting to resolve the database connection before the application has finished initializing. Even if we address the immediate problem (a missing dictionary key), this would result in querying the database before branching support has been initialized.

Ideally, plugins should [avoid interacting with the database](https://docs.djangoproject.com/en/5.1/ref/applications/#django.apps.AppConfig.ready) under the `ready()` method. Can the call to `get_config()` be moved elsewhere?

**Comment by jeremystretch** [comment]
> Ideally, plugins should [avoid interacting with the database](https://docs.djangoproject.com/en/5.1/ref/applications/#django.apps.AppConfig.ready) under the ready() method.

You should also see a warning to this effect when doing so:

```
RuntimeWarning: Accessing the database during app initialization is discouraged. To fix this warning, avoid executing queries in AppConfig.ready() or when your app modules are imported.
 ```

What we can do for now is have the database router return immediately (and log a warning) if branching support has not been initialized. This will apply the default database routing provided by Django.
