### ISSUE TITLE
DATABASES must be a DynamicSchemaDict instance.

### ISSUE THREAD

**Issue by Zheer09** [netboxlabs/netbox-branching#137]
### Plugin Version

0.5.0

### NetBox Version

4.1.0

### Python Version

3.12.3

### Steps to Reproduce

I am using docker for installing the netbox and to install plugins ,netbox branching is in the last plugins in the list as it has been documented i have added `local_settings.py` in the samne configuration directory

My postgresql version from docker compose file `12.20-alpine`

```python
import sys
import os

from netbox_branching.utilities import DynamicSchemaDict

# Add the parent directory of 'config' to the Python path
sys.path.append('/etc/netbox')

from config.configuration import DATABASE

# Wrap DATABASES with DynamicSchemaDict for dynamic schema support
DATABASES = DynamicSchemaDict({
    'default': DATABASE,
})

# Employ our custom database router
DATABASE_ROUTERS = [
    'netbox_branching.database.BranchAwareRouter',
]
```

**Note**: I have to add `sys.path.append('/etc/netbox')`  in order to make `from config.configuration import DATABASE` work

My Dockerfile

```Dockerfile
FROM netboxcommunity/netbox:4.1.0

COPY ./plugin_requirements.txt /opt/netbox/
RUN /opt/netbox/venv/bin/pip install  --no-warn-script-location -r /opt/netbox/plugin_requirements.txt

# These lines are only required if your plugin has its own static files.
COPY configuration/configuration.py /etc/netbox/config/configuration.py
COPY configuration/plugins.py /etc/netbox/config/plugins.py
COPY configuration/local_settings.py /etc/netbox/config/local_settings.py
RUN SECRET_KEY='dumy' /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py migrate
RUN SECRET_KEY='dumy' /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py collectstatic --no-input
```

plugins.py

```python
# Add your plugins and plugin settings here.
# Of course uncomment this file out.

# To learn how to build images with your required plugins
# See https://github.com/netbox-community/netbox-docker/wiki/Using-Netbox-Plugins

PLUGINS = [
    'netbox_dns',     'netbox_reorder_rack',     'netbox_topology_views',     'netbox_contract',     'netbox_slm',     'netbox_branching'  ]

PLUGINS_CONFIG = {
    "netbox_dns": {},     "netbox_reorder_rack": {},     "netbox_topology_views": {},     "netbox_contract": {},     "netbox_slm": {},     "netbox_branching": {}  }r
```

### Expected Behavior

To install and work properly 

### Observed Behavior

I got this error while building the docker file in this line

`RUN SECRET_KEY='dumy' /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py migrate`

```
5.070 🧬 loaded config '/etc/netbox/config/local_settings.py'                                                                                                                                                                       
5.070 🧬 loaded config '/etc/netbox/config/logging.py'
5.070 🧬 loaded config '/etc/netbox/config/plugins.py'
5.070 Traceback (most recent call last):
5.070   File "/opt/netbox/netbox/manage.py", line 10, in <module>
5.070     execute_from_command_line(sys.argv)
5.070   File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
5.070     utility.execute()
5.070   File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute
5.070     django.setup()
5.070   File "/opt/netbox/venv/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
5.070     apps.populate(settings.INSTALLED_APPS)
5.070   File "/opt/netbox/venv/lib/python3.12/site-packages/django/apps/registry.py", line 124, in populate
5.070     app_config.ready()
5.070   File "/opt/netbox/venv/lib/python3.12/site-packages/netbox_branching/__init__.py", line 39, in ready
5.070     raise ImproperlyConfigured(
5.070 django.core.exceptions.ImproperlyConfigured: netbox_branching: DATABASES must be a DynamicSchemaDict instance.
```

**Comment by chris199512** [comment]
Set the path of local_settings.py to /opt/netbox/netbox/netbox/local_settings.py
This works for me

**Comment by cruse1977** [comment]
I've removed the label bug here and this isn't a branching issue - this occurs due to NetBox docker not exposing the local_settings.py into the container. 

 This is one way - (original source: https://netdev-community.slack.com/archives/C01P0FRSXRV/p1723619694312009 - which is me too)
 
```
* create the file local_settings.py in the root folder (ie: NOT in configuration/) as per the installation guide

* add the following to the volumes: section of docker-compose.yml

    - type: bind
      source: ./local_settings.py
      target: /opt/netbox/netbox/netbox/local_settings.py
      read_only: true
```

**Comment by Zheer09** [comment]
Okay great that worked, but would appreciated if this was documented some where for docker environment.  

Thanks @chris199512 @cruse1977

**Comment by cruse1977** [comment]
Appreciated, but this would need to be done within the netbox docker
project as it's docker specific. I'll raise and issue there if not already.
