### ISSUE TITLE
Plugin not working with remote database via SSL

### ISSUE THREAD

**Issue by blipnet** [netboxlabs/netbox-branching#165]
### Plugin Version

0.5.1

### NetBox Version

4.1.4

### Python Version

3.12

### Steps to Reproduce

Can't access branches when running database remote and via SSL.
It seems lite it doesn't provide the OPTIONS when using branches.

1 create new branch
2 Change to the new branch

### Expected Behavior

I should be able to access the new Branch

### Observed Behavior

Can't access branches when running database remote and via SSL.
It seems lite it doesn't provide the OPTIONS when using branches.

configuration.py
```
DATABASE = {
    'ENGINE': 'django.db.backends.postgresql',  # Database engine
    'NAME': 'netbox',         # Database name
    'USER': 'netbox',        # PostgreSQL username
    'PASSWORD': '*****',           # PostgreSQL password
    'HOST': '<FQDN>',
    'PORT': '6432',           # Database port (leave blank for default)
    'CONN_MAX_AGE': None,
    'OPTIONS': {
       'connect_timeout': '2',
       'tcp_user_timeout': '3000',
       'sslmode': 'verify-ca',
       'sslrootcert': '/etc/pki/pgdb/certs/pgdb1.crt',
       'application_name': 'netbox'
    }
}
```

Traceback:
```
Environment:


Request Method: GET
Request URL: https://netbox-dev.*********.com/

Django Version: 5.0.9
Python Version: 3.12.6
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'django.forms',
 'corsheaders',
 'debug_toolbar',
 'django_filters',
 'django_htmx',
 'django_tables2',
 'django_prometheus',
 'strawberry_django',
 'mptt',
 'rest_framework',
 'social_django',
 'taggit',
 'timezone_field',
 'core',
 'account',
 'circuits',
 'dcim',
 'ipam',
 'extras',
 'tenancy',
 'users',
 'utilities',
 'virtualization',
 'vpn',
 'wireless',
 'django_rq',
 'drf_spectacular',
 'drf_spectacular_sidecar',
 'django3_saml2_nbplugin.Django3AuthSAML2Plugin',
 'nsa_circuits.NSACircuitConfig',
 'template_extensions.TemplateExtensionsConfig',
 'netbox_ddns.NetBoxDDNSConfig',
 'netbox_branching.AppConfig',
 'netbox_reorder_rack.NetboxReorderRackConfig']
Installed Middleware:
['strawberry_django.middlewares.debug_toolbar.DebugToolbarMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django_htmx.middleware.HtmxMiddleware',
 'netbox.middleware.RemoteUserMiddleware',
 'netbox.middleware.CoreMiddleware',
 'netbox.middleware.MaintenanceModeMiddleware',
 'netbox_branching.middleware.BranchMiddleware']



Traceback (most recent call last):
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 187, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^

During handling of the above exception ('SessionStore' object has no attribute '_session_cache'), another exception occurred:
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/db/backends/base/base.py", line 275, in ensure_connection
    self.connect()
    ^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/db/backends/postgresql/base.py", line 277, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/psycopg/connection.py", line 119, in connect
    raise last_ex.with_traceback(None)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The above exception (connection failed: unsupported startup parameter in options: search_path
FATAL:  SSL required) was the direct cause of the following exception:
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/netbox/utilities/views.py", line 37, in dispatch
    if settings.LOGIN_REQUIRED and not request.user.is_authenticated:
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/utils/functional.py", line 251, in inner
    self._setup()
    ^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/utils/functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/contrib/auth/middleware.py", line 33, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/contrib/auth/middleware.py", line 13, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/contrib/auth/__init__.py", line 209, in get_user
    user_id = _get_user_session_key(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/contrib/auth/__init__.py", line 62, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 53, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 192, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/contrib/sessions/backends/db.py", line 42, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/contrib/sessions/backends/db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
           
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
    ^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/db/backends/base/base.py", line 316, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/db/backends/base/base.py", line 292, in _cursor
    self.ensure_connection()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/db/backends/base/base.py", line 274, in ensure_connection
    with self.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/db/backends/base/base.py", line 275, in ensure_connection
    self.connect()
    ^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/django/db/backends/postgresql/base.py", line 277, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.4/venv/lib64/python3.12/site-packages/psycopg/connection.py", line 119, in connect
    raise last_ex.with_traceback(None)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: OperationalError at /
Exception Value: connection failed: unsupported startup parameter in options: search_path
FATAL:  SSL required
```

**Comment by blipnet** [comment]
This might be related to pgbouncer and that search_path is not supported

Adding this to the .ini config file and it seems to fixed the issue
 ```
   ignore_startup_parameters:  search_path
```

**Comment by jeremystretch** [comment]
PostgreSQL's [search path](https://www.postgresql.org/docs/current/ddl-schemas.html#DDL-SCHEMAS-PATH) is used to effect branching. The plugin will not work without it.

**Comment by tyler-8** [comment]
For future searchers, I've started a related discussion on pgbouncer and netbox-branching here: https://github.com/netboxlabs/netbox-branching/discussions/191
